services:
  app:
    image: node:20.9
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "npm install && npm run build && node .output/server/index.mjs"
    ports:
      - 3000:3000
    env_file:
      - .env